// Generated by Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
#ifndef PECUNPUSHSDK_SWIFT_H
#define PECUNPUSHSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PecunPushSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12PecunPushSDK23PecunBaseViewController")
@interface PecunBaseViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboardSegue;
@class UITextField;

SWIFT_CLASS("_TtC12PecunPushSDK30CreateSecretCodeViewController")
@interface CreateSecretCodeViewController : PecunBaseViewController
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)viewWillAppear:(BOOL)animated;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK12PushDelegate_")
@protocol PushDelegate
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


@interface CreateSecretCodeViewController (SWIFT_EXTENSION(PecunPushSDK)) <PushDelegate>
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


@interface CreateSecretCodeViewController (SWIFT_EXTENSION(PecunPushSDK)) <UITextFieldDelegate>
@end


SWIFT_CLASS("_TtC12PecunPushSDK12Header1Label")
@interface Header1Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK12Header2Label")
@interface Header2Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK12Header3Label")
@interface Header3Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK28InfoSecretCodeViewController")
@interface InfoSecretCodeViewController : PecunBaseViewController
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK21LinkBiometricDelegate_")
@protocol LinkBiometricDelegate
- (void)linkBiometricFinishOk;
- (void)linkBiometricFinishKo;
@end


SWIFT_CLASS("_TtC12PecunPushSDK27LinkBiometricViewController")
@interface LinkBiometricViewController : PecunBaseViewController <UITextFieldDelegate>
- (void)viewWillAppear:(BOOL)animated;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK25ModifyPhoneViewController")
@interface ModifyPhoneViewController : PecunBaseViewController <UITextFieldDelegate>
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)viewWillAppear:(BOOL)animated;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ModifyPhoneViewController (SWIFT_EXTENSION(PecunPushSDK)) <PushDelegate>
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC12PecunPushSDK33ModifySecretCodeSCAViewController")
@interface ModifySecretCodeSCAViewController : PecunBaseViewController
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ModifySecretCodeSCAViewController (SWIFT_EXTENSION(PecunPushSDK)) <PushDelegate>
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


@interface ModifySecretCodeSCAViewController (SWIFT_EXTENSION(PecunPushSDK)) <UITextFieldDelegate>
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK18PSD2CallerDelegate_")
@protocol PSD2CallerDelegate
- (void)resendCall;
@end


SWIFT_CLASS("_TtC12PecunPushSDK24PecunAlertViewController")
@interface PecunAlertViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIFont;

SWIFT_CLASS("_TtC12PecunPushSDK15PecunAppearence")
@interface PecunAppearence : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonColor;)
+ (UIColor * _Nonnull)buttonColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonBorderColor;)
+ (UIColor * _Nonnull)buttonBorderColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonBorderColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonColorHighlight;)
+ (UIColor * _Nonnull)buttonColorHighlight SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonColorHighlight:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonBorderColorHighlight;)
+ (UIColor * _Nonnull)buttonBorderColorHighlight SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonBorderColorHighlight:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonTextColor;)
+ (UIColor * _Nonnull)buttonTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonSecondaryColor;)
+ (UIColor * _Nonnull)buttonSecondaryColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonSecondaryColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonSecondaryBorderColor;)
+ (UIColor * _Nonnull)buttonSecondaryBorderColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonSecondaryBorderColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonSecondaryColorHighlight;)
+ (UIColor * _Nonnull)buttonSecondaryColorHighlight SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonSecondaryColorHighlight:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonSecondaryBorderColorHighlight;)
+ (UIColor * _Nonnull)buttonSecondaryBorderColorHighlight SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonSecondaryBorderColorHighlight:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull buttonSecondaryTextColor;)
+ (UIColor * _Nonnull)buttonSecondaryTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonSecondaryTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable header1LabelFont;)
+ (UIFont * _Nullable)header1LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader1LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable header2LabelFont;)
+ (UIFont * _Nullable)header2LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader2LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable header3LabelFont;)
+ (UIFont * _Nullable)header3LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader3LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable header4LabelFont;)
+ (UIFont * _Nullable)header4LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader4LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nonnull subtitle1LabelFont;)
+ (UIFont * _Nonnull)subtitle1LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle1LabelFont:(UIFont * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nonnull subtitle2LabelFont;)
+ (UIFont * _Nonnull)subtitle2LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle2LabelFont:(UIFont * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nonnull subtitle3LabelFont;)
+ (UIFont * _Nonnull)subtitle3LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle3LabelFont:(UIFont * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable text1LabelFont;)
+ (UIFont * _Nullable)text1LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setText1LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable text2LabelFont;)
+ (UIFont * _Nullable)text2LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setText2LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nullable text3LabelFont;)
+ (UIFont * _Nullable)text3LabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setText3LabelFont:(UIFont * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIFont * _Nonnull PinLabelFont;)
+ (UIFont * _Nonnull)PinLabelFont SWIFT_WARN_UNUSED_RESULT;
+ (void)setPinLabelFont:(UIFont * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull header1LabelTextColor;)
+ (UIColor * _Nonnull)header1LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader1LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull header2LabelTextColor;)
+ (UIColor * _Nonnull)header2LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader2LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull header3LabelTextColor;)
+ (UIColor * _Nonnull)header3LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeader3LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull subtitle1LabelTextColor;)
+ (UIColor * _Nonnull)subtitle1LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle1LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull subtitle12LabelTextColor;)
+ (UIColor * _Nonnull)subtitle12LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle12LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull subtitle2LabelTextColor;)
+ (UIColor * _Nonnull)subtitle2LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle2LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull subtitle22LabelTextColor;)
+ (UIColor * _Nonnull)subtitle22LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle22LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull subtitle3LabelTextColor;)
+ (UIColor * _Nonnull)subtitle3LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSubtitle3LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull text1LabelTextColor;)
+ (UIColor * _Nonnull)text1LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setText1LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull text2LabelTextColor;)
+ (UIColor * _Nonnull)text2LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setText2LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull text3LabelTextColor;)
+ (UIColor * _Nonnull)text3LabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setText3LabelTextColor:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull PinLabelTextColor;)
+ (UIColor * _Nonnull)PinLabelTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setPinLabelTextColor:(UIColor * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK17PecunBaseDelegate_")
@protocol PecunBaseDelegate
@property (nonatomic, strong) id <PushDelegate> _Null_unspecified delegate;
@end



SWIFT_CLASS("_TtC12PecunPushSDK13PecunPinField")
@interface PecunPinField : UITextField
@property (nonatomic, copy) NSString * _Nullable text;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)insertText:(NSString * _Nonnull)text;
- (void)deleteBackward;
@property (nonatomic, readonly) BOOL hasText;
@property (nonatomic) UIKeyboardAppearance keyboardAppearance;
@property (nonatomic) UIKeyboardType keyboardType;
- (void)reloadInputViews;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (BOOL)becomeFirstResponder;
- (void)reloadAppearance;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ValidateSCAViewController;
@protocol PendingPurchaseDelegate;
@class PendingPurchaseViewController;

SWIFT_CLASS("_TtC12PecunPushSDK9PecunPush")
@interface PecunPush : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable uuid;)
+ (NSString * _Nullable)uuid SWIFT_WARN_UNUSED_RESULT;
+ (void)setUuid:(NSString * _Nullable)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)isDeviceTokenizedWithIdentityDocument:(NSString * _Nonnull)identityDocument SWIFT_WARN_UNUSED_RESULT;
+ (void)registerWithNumMp:(NSString * _Nonnull)numMp token:(NSString * _Nullable)token error:(NSError * _Nullable)error completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)unregisterWithNumMp:(NSString * _Nonnull)numMp completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (void)validateWithOtp:(NSString * _Nonnull)otp completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
+ (ValidateSCAViewController * _Nonnull)openValidateSCAOperationWithUserId:(NSString * _Nonnull)userId uuid:(NSString * _Nonnull)uuid delegate:(id <PSD2CallerDelegate> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
+ (PendingPurchaseViewController * _Nonnull)openPendingPurchaseWithDelegate:(id <PendingPurchaseDelegate> _Nonnull)delegate identityDocument:(NSString * _Nonnull)identityDocument otpCode:(NSString * _Nonnull)otpCode SWIFT_WARN_UNUSED_RESULT;
+ (LinkBiometricViewController * _Nonnull)openLinkBiometricWithDelegate:(id <LinkBiometricDelegate> _Nonnull)delegate userIdentity:(NSString * _Nonnull)userIdentity SWIFT_WARN_UNUSED_RESULT;
+ (CreateSecretCodeViewController * _Nonnull)createSecretCodeWithNumMp:(NSString * _Nonnull)numMp delegate:(id <PSD2CallerDelegate> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
+ (ModifySecretCodeSCAViewController * _Nonnull)modifySecretCodeWithNumMp:(NSString * _Nonnull)numMp delegate:(id <PSD2CallerDelegate> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
+ (ModifyPhoneViewController * _Nonnull)modifyPhoneWithNumMp:(NSString * _Nonnull)numMp userId:(NSString * _Nonnull)userId delegate:(id <PSD2CallerDelegate> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12PecunPushSDK15PecunPushButton")
@interface PecunPushButton : UIButton
- (void)awakeFromNib;
- (void)setTitleTextWithTitle:(NSString * _Nonnull)title;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK24PecunPushSecondaryButton")
@interface PecunPushSecondaryButton : UIButton
- (void)awakeFromNib;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK23PendingPurchaseDelegate_")
@protocol PendingPurchaseDelegate
- (void)PendingPurchaseFinishOk;
- (void)PendingPurchaseFinishKo;
@end


SWIFT_CLASS("_TtC12PecunPushSDK29PendingPurchaseViewController")
@interface PendingPurchaseViewController : PecunBaseViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface PendingPurchaseViewController (SWIFT_EXTENSION(PecunPushSDK)) <UITextFieldDelegate>
@end


@interface PendingPurchaseViewController (SWIFT_EXTENSION(PecunPushSDK)) <PendingPurchaseDelegate>
- (void)PendingPurchaseFinishOk;
- (void)PendingPurchaseFinishKo;
@end


@interface PendingPurchaseViewController (SWIFT_EXTENSION(PecunPushSDK)) <PushDelegate>
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


SWIFT_PROTOCOL("_TtP12PecunPushSDK9Presenter_")
@protocol Presenter
- (void)prepareFor:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
@end



SWIFT_PROTOCOL("_TtP12PecunPushSDK6Router_")
@protocol Router
@property (nonatomic, readonly, strong) UIViewController * _Null_unspecified viewController;
- (void)prepareFor:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
@end


SWIFT_CLASS("_TtC12PecunPushSDK15SubTitle12Label")
@interface SubTitle12Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK14SubTitle1Label")
@interface SubTitle1Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK15SubTitle22Label")
@interface SubTitle22Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK14SubTitle2Label")
@interface SubTitle2Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK14SubTitle3Label")
@interface SubTitle3Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK10Text1Label")
@interface Text1Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK10Text2Label")
@interface Text2Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12PecunPushSDK10Text3Label")
@interface Text3Label : UILabel
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSAttributedString;

/// An object of the class has a customized placeholder label which has animations on the beginning and ending editing.
SWIFT_CLASS("_TtC12PecunPushSDK24TweePlaceholderTextField")
@interface TweePlaceholderTextField : UITextField
/// Minimum font size for the custom placeholder.
@property (nonatomic) IBInspectable CGFloat minimumPlaceholderFontSize;
/// Original (maximum) font size for the custom placeholder.
@property (nonatomic) IBInspectable CGFloat originalPlaceholderFontSize;
/// Placeholder animation duration.
@property (nonatomic) IBInspectable double placeholderDuration;
/// Color of custom placeholder.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable placeholderColor;
/// The string that is displayed when there is no other text in the text field.
@property (nonatomic, copy) IBInspectable NSString * _Nullable tweePlaceholder;
/// The current text that is displayed by the label.
@property (nonatomic, copy) NSString * _Nullable text;
/// The styled text displayed by the text field.
@property (nonatomic, strong) NSAttributedString * _Nullable attributedText;
/// The technique to use for aligning the text.
@property (nonatomic) NSTextAlignment textAlignment;
/// The font used to display the text.
@property (nonatomic, strong) UIFont * _Nullable font;
/// :nodoc:
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (void)awakeFromNib;
/// :nodoc:
- (void)layoutSubviews;
@end


/// An object of the class can show bottom line permanently.
SWIFT_CLASS("_TtC12PecunPushSDK21TweeBorderedTextField")
@interface TweeBorderedTextField : TweePlaceholderTextField
/// Color of bottom line.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull lineColor;
/// Width of bottom line.
@property (nonatomic) IBInspectable CGFloat lineWidth;
/// :nodoc:
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (void)layoutSubviews;
@end


/// An object of the class can show animated bottom line when a user begins editing.
SWIFT_CLASS("_TtC12PecunPushSDK19TweeActiveTextField")
@interface TweeActiveTextField : TweeBorderedTextField
/// Color of line that appears when a user begins editing.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull activeLineColor;
/// Width of line that appears when a user begins editing.
@property (nonatomic) IBInspectable CGFloat activeLineWidth;
/// Width of line that appears when a user begins editing.
@property (nonatomic) IBInspectable double animationDuration;
/// :nodoc:
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (void)layoutSubviews;
@end


/// An object of the class can show the custom info label under text field.
SWIFT_CLASS("_TtC12PecunPushSDK23TweeAttributedTextField")
@interface TweeAttributedTextField : TweeActiveTextField
/// Animation duration for showing and hiding the info label.
@property (nonatomic) IBInspectable double infoAnimationDuration;
/// Color of info text.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull infoTextColor;
/// Font size of info text. If you want to change font use <code>infoLabel</code> property.
@property (nonatomic) IBInspectable CGFloat infoFontSize;
/// :nodoc:
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// :nodoc:
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Shows info label with/without animation.
/// \param attrText Custom attributed text to show.
///
/// \param animated By default is <code>true</code>.
///
- (void)showAttributtedInfo:(NSAttributedString * _Nonnull)attrText animated:(BOOL)animated;
/// Shows info label with/without animation.
/// \param text Custom text to show.
///
/// \param animated By default is <code>true</code>.
///
- (void)showInfo:(NSString * _Nonnull)text animated:(BOOL)animated;
/// Hides the info label with animation or not.
/// \param animated By default is <code>true</code>.
///
- (void)hideInfoWithAnimated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC12PecunPushSDK14Text3TextField")
@interface Text3TextField : TweeAttributedTextField
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end











SWIFT_CLASS("_TtC12PecunPushSDK25ValidateSCAViewController")
@interface ValidateSCAViewController : PecunBaseViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ValidateSCAViewController (SWIFT_EXTENSION(PecunPushSDK)) <PushDelegate>
- (void)setPushCodeWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
